name: seckit
description: Secure cryptographic utilities for Dart JWT authentication, field encryption, password hashing, and deterministic hashing.
version: 1.0.4
homepage: https://github.com/bakhbk/seckit
repository: https://github.com/bakhbk/seckit
issue_tracker: https://github.com/bakhbk/seckit/issues

environment:
  sdk: "^3.0.0"

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

# Add regular dependencies here.
dependencies:
  path: ^1.9.1
  crypto: ^3.0.6
  encrypt: ^5.0.3
  jaguar_jwt: ^3.0.0
  async_lite: ^0.0.7
  bcrypt: ^1.1.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
