name: seckit
description: Secure cryptographic utilities for Dart JWT authentication, field encryption, password hashing, and deterministic hashing.
version: 1.0.5
homepage: https://github.com/bakhbk/seckit
repository: https://github.com/bakhbk/seckit
issue_tracker: https://github.com/bakhbk/seckit/issues

environment:
  sdk: "^3.2.0"

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

# Add regular dependencies here.
dependencies:
  path: ^1.8.3
  crypto: ^3.0.3
  encrypt: ^5.0.3
  jaguar_jwt: ^3.0.0
  async_lite: ^1.0.0
  bcrypt: ^1.1.3

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.0
